### ISSUE TITLE
How Can add title Taxi beside the blip in right in map

### ISSUE THREAD

**Issue by FuTuRNeT** [ESX-Org/esx_taxijob#17]
Hi, 
How Can add title Taxi beside the blip in right in map, becaue there is nothing next to the blip

Best Regards
Akram

**Comment by xnubil** [comment]
There is a blip limit, are you sure you aren't over the limit?  Running the version of the script available today, the name "Taxi" is beside my blip.

**Comment by RedAlex** [comment]
Test on last version taxi is on the blip
![taxi](https://user-images.githubusercontent.com/855331/44004969-84c9714c-9e39-11e8-8f0a-5bb231a88749.jpg)
