### ISSUE TITLE
taci blip is here but nohing happens...

### ISSUE THREAD

**Issue by mangamaniacs2064** [ESX-Org/esx_taxijob#19]
i go to the taxi blip on the map but there is nothing to do.,,, why? here is my server.cfg file:

`
# you probably don't want to change these!
# only change them if you're using a server with multiple network interfaces
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

set es_enableCustomData 1

start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start scoreboard
start playernames
start fivem-map-hipster
start fivem-map-skater
start baseevents
start mysql-async
start essentialmode

start esplugin_mysql
start es_admin2
start async
start runcode

start esx_menu_default
start esx_menu_list
start esx_menu_dialog
start es_extended
start esx_license

start esx_vehicleshop
start esx_society
start cron
start esx_addonaccount
start esx_addoninventory
start esx_billing
start esx_service
start esx_datastore

start esx_jobs
start esx_joblisting
start esx_taxijob

start instance
start skinchanger
start esx_skin

`

can you tell me if you see why it cant start,,? i executed the taxi sql file too in my database.. so i wonder...

**Comment by TemptressTeelia** [comment]
Dude you put your license key and passwords for everyone to see! Jesus! Plus your config isn’t in esx order. You have some essentials lower.  We do t need to see all the passwords stuff just the start resources. You will have to change all your passwords, everything. Good luck.

**Comment by TemptressTeelia** [comment]
Also if you press delete the. You get missions.

**Comment by mangamaniacs2064** [comment]
my mistake for that but i am making a test server anyway.. no big deal..but i press E button didnt work.. but you say i have to press delete button?
