### ISSUE TITLE
[ISSUE] [Mission does not start after last update] [must_be_in_taxi/car issue] 

### ISSUE THREAD

**Issue by djowdobom** [ESX-Org/esx_taxijob#21]
Hello, i'm having a trouble with the new taxijob, I just cant start mission with F6 option, i tried with all grades, it keep saying "you must be in a taxi or a vehicle.." when i'm already on it.

Thanks!

**Comment by TemptressTeelia** [comment]
Press del. That starts the missions. It says in the script

**Comment by djowdobom** [comment]
Actually, they update to F6 command. Thats where i'm having issue with already on taxi/veh

**Comment by TemptressTeelia** [comment]
Oh really? Cause we have the old one and we just use our own cars tbh. I will have to test it again now.

**Comment by djowdobom** [comment]
adding some infos:
does not trigger any error in console or f8,
runing all esx-org original files,
have any errors in old one version. But i want to keep it updated.

**Comment by ElPumpo** [comment]
What do you mean by 'it doesnt work'
- you must sit in the driver seat
- you must drive an authorized vehicle

**Comment by djowdobom** [comment]
Hello Pumpo, i know how the job used to work. But now, its not working even in the driver seat and authorized vehicle keep saying that i must be in a taxi... when i'm already on it!

**Comment by XxFri3ndlyxX** [comment]
Same here can't start mission. Even if i wear the taxi clothe and drive the taxi that you spawn.

**Comment by orakah** [comment]
#22

**Comment by ElPumpo** [comment]
Woops. My bad - fixed now.
