### ISSUE TITLE
npc job

### ISSUE THREAD

**Issue by orakah** [ESX-Org/esx_taxijob#23]
I don't know if it's meant to be like this, but if you look at the lines (`638: if IsPedInAnyVehicle(playerPed,  false) and GetEntitySpeed(playerPed) > 0 then`) and (`646: if OnJob and IsPedInAnyVehicle(playerPed,  false) and GetEntitySpeed(playerPed) > 0 then`) the player can't get the npc job if he is standing still, only if he is moving.

**Comment by EGUltraTM** [comment]
yes npc jobs doesnt work

**Comment by ElPumpo** [comment]
It works just fine. You're supposed to drive around until you get close to a location in the config where you'll find a customer.
