### ISSUE TITLE
F6 menu not opening

### ISSUE THREAD

**Issue by M1kuuu** [ESX-Org/esx_taxijob#24]
F6 menu doesn't open. I have all the latest versions of esx_menu scripts.

**Comment by XxFri3ndlyxX** [comment]
Yup same for me. It wasn't working for me on last update and same goes for this update.

**Comment by djowdobom** [comment]
try to "Config.EnablePlayerManagement     = true" line 5 in esx_taxijob/config.lua

**Comment by ElPumpo** [comment]
Try the latest version and report back thanks.
