### ISSUE TITLE
Can't open boss menu

### ISSUE THREAD

**Issue by KingRyuShin** [ESX-Org/esx_taxijob#28]
I set myself as the boss and I can't open the bossmenu
nothing happen but on other job it work fine, society_taxi is created in the bdd

**Comment by Blackwave78** [comment]
Same problem and no npc job

**Comment by Blackwave78** [comment]
change 

		if IsControlJustReleased(0, Keys['F6']) and IsInputDisabled(0) and not IsDead and Config.EnablePlayerManagement and ESX.PlayerData.job and ESX.PlayerData.job.name == 'taxi' then
			OpenMobileTaxiActionsMenu()
		end

by 
		if IsControlJustReleased(0, Keys['F6']) and not isDead and ESX.PlayerData.job and ESX.PlayerData.job.name == 'taxi' then
			OpenMobileTaxiActionsMenu()
		end
