### ISSUE TITLE
F6 FIX

### ISSUE THREAD

**Issue by XxFri3ndlyxX** [ESX-Org/esx_taxijob#31]
If some of you for some reason the f6 wont work out of the box. 
Then replace the f6 control line with this
`if ( IsControlJustReleased( 0, 167 ) or IsDisabledControlJustReleased( 0, 167 ) ) and GetLastInputMethod( 0 ) and not isDead and Config.EnablePlayerManagement and ESX.PlayerData.job and ESX.PlayerData.job.name == 'taxi' then`

**Comment by ponduzn** [comment]
> If some of you for some reason the f6 wont work out of the box.
> Then replace the f6 control line with this
> `if ( IsControlJustReleased( 0, 167 ) or IsDisabledControlJustReleased( 0, 167 ) ) and GetLastInputMethod( 0 ) and not isDead and Config.EnablePlayerManagement and ESX.PlayerData.job and ESX.PlayerData.job.name == 'taxi' then`

Actually this did not work for me, but a fix i found was way easier.
Just replace this:

> if IsControlJustReleased(0, Keys['F6'])

with this:

> if IsControlJustReleased(0, 167)

Not sure why as the key is declared F6 in the file also, but it works.
