### ISSUE TITLE
F6 Menu doesn't open when in vehicle

### ISSUE THREAD

**Issue by brynnie1** [ESX-Org/esx_taxijob#40]
So My F6 menu works when i'm out of the vehicle but as soon as I get in I can't use it therefore I cannot bill customers/ start NPC missions. I have to do this out of the vehicle is there any fix for this. Thanks

**Comment by rafakid** [comment]
I just do not open the menu when I press F6

**Comment by XvenDeR** [comment]
mine dont work at all 🗡

**Comment by TheRealDadbeard** [comment]
Yeah I can't open the menu either.

**Comment by gogomalchev** [comment]
I have the same problem. F6 menu doesn't work

**Comment by shinigami2597** [comment]
set 
Config.EnablePlayerManagement     = true 
in config.lua

**Comment by XvenDeR** [comment]
Yeah we know, but dont work in vehicle.

**Comment by shinigami2597** [comment]
about how it doesn't work in vehicle then you have to provide me more information. I basically need all your client/ main.lua or if you don't want to share it then i will assume that the solution might be with this code. Check if your code in clinet / main.lua is exactly the same as this one: 

		if IsControlJustReleased(0, 167) and IsInputDisabled(0) and not IsDead and Config.EnablePlayerManagement and ESX.PlayerData.job and ESX.PlayerData.job.name == 'taxi' then
			OpenMobileTaxiActionsMenu()
		end
	end
end)

**Comment by XvenDeR** [comment]
It's from this source code, the same. And to be honest I just tried this just now after restart and it works... But still I don't know what causes sometime menu to not work while in vehicle or at all. It works now and nothing I have changed, so I have no clue. I think that's it for now... I wonder how it is for others now?

**Comment by shinigami2597** [comment]
Yeah, i have no clue either. Cuz i downloaded from this source code too. Then i edited this and that and it still work perfectly .

**Comment by brynnie1** [comment]
> about how it doesn't work in vehicle then you have to provide me more information. I basically need all your client/ main.lua or if you don't want to share it then i will assume that the solution might be with this code. Check if your code in clinet / main.lua is exactly the same as this one:
> 
> ```
> 	if IsControlJustReleased(0, 167) and IsInputDisabled(0) and not IsDead and Config.EnablePlayerManagement and ESX.PlayerData.job and ESX.PlayerData.job.name == 'taxi' then
> 		OpenMobileTaxiActionsMenu()
> 	end
> end
> ```
> 
> end)

So I have player management enabled and the code exactly how yours is set, however it still not working when I get in a vehicle I cannot press F6., if i'm outside the car then it opens up, but for me to bill someone I have to be in the car.

**Comment by DocBurN** [comment]
My bet.. you have vMenu installed.. try F8... into the console... "stop vMenu".. and check if F6 work now.. then go have fun with vMenu..

**Comment by brynnie1** [comment]
No longer use Fivem
