### ISSUE TITLE
Taxi not spawing  

### ISSUE THREAD

**Issue by FlaxLowbreeze** [ESX-Org/esx_taxijob#9]
Taxi do not spawn when you take taxi job an go for the taxi 

Server error code 

Error running call reference function for resource esx_society: server/main.lua:310: attempt to index a n
local 'store')
stack traceback:
        server/main.lua:310: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:317: in function <citizen:/scripting/lua/scheduler.lua:308>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:243: in function 'TriggerEventInternal'
        (...tail calls...)
        server/main.lua:309: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:317: in function <citizen:/scripting/lua/scheduler.lua:308>
Error running system event handling function for resource esx_datastore: citizen:/scripting/lua/scheduler
ailed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:378: in local 'cb'
        server/main.lua:90: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>

**Comment by DankVybez** [comment]
Seems like im getting the same error.. Is there something I am missing? So far no other problems from what I have tested.
![taxijoberror](https://user-images.githubusercontent.com/30758374/30501771-b9cce20a-9a31-11e7-8c7e-9bb32724644f.png)
![taxijoberror2](https://user-images.githubusercontent.com/30758374/30501775-bbf9f3f6-9a31-11e7-9703-5778cfa0ef5d.png)

**Comment by Major401** [comment]
How do i fix this?

Error running call reference function for resource esx_society: server/main.lua:363: attempt to index a nil value (local 'store')
stack traceback:
        server/main.lua:363: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:317: in function <citizen:/scripting/lua/scheduler.lua:308>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:243: in function 'TriggerEventInternal'
        (...tail calls...)
        server/main.lua:362: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:317: in function <citizen:/scripting/lua/scheduler.lua:308>
Error running system event handling function for resource esx_datastore: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:378: in local 'cb'
        server/main.lua:106: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
hitch warning: frame time of 253 milliseconds

**Comment by DankVybez** [comment]
@Major401 make sure that your taxi job config has the same as your vehicle shop. Config.EnableSocietyOwnedVehicles = false. or
Config.EnableSocietyOwnedVehicles = true

Just make sure all your jobs match to your vehicleshop and you should be good.

**Comment by JaroSound** [comment]
@DankVybez i have the same problem. And the solution is not workin...

**Comment by jeedzzz** [comment]
Error running call reference function for resource esx_society: citizen:/scripting/lua/scheduler.lua:348: server/main.lua:363: attempt to index a nil value (local 'store')
stack traceback:
        server/main.lua:363: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:334: in function <citizen:/scripting/lua/scheduler.lua:333>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:333: in function <citizen:/scripting/lua/scheduler.lua:332>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:348: in function <citizen:/scripting/lua/scheduler.lua:319>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:332: in function <citizen:/scripting/lua/scheduler.lua:319>
Error running system event handling function for resource esx_datastore: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:560: in local 'cb'
        server/main.lua:106: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:173>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:173: in function <citizen:/scripting/lua/scheduler.lua:138>
hitch warning: frame time of 484 milliseconds
Error running call reference function for resource esx_society: citizen:/scripting/lua/scheduler.lua:348: server/main.lua:363: attempt to index a nil value (local 'store')
stack traceback:
        server/main.lua:363: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:334: in function <citizen:/scripting/lua/scheduler.lua:333>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:333: in function <citizen:/scripting/lua/scheduler.lua:332>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:348: in function <citizen:/scripting/lua/scheduler.lua:319>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:332: in function <citizen:/scripting/lua/scheduler.lua:319>
Error running system event handling function for resource esx_datastore: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:560: in local 'cb'
        server/main.lua:106: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:173>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:173: in function <citizen:/scripting/lua/scheduler.lua:138>

Config.EnableSocietyOwnedVehicles are the same as vehicle shop. already

**Comment by SkillDie** [comment]
Modify your config.lua like this:

Config.EnableSocietyOwnedVehicles = false

false not true

Enjoy ;)
